# ~/Projects/datum-config/backups.nix
{
  config,
  pkgs,
  ...
}: {
  # ======================================================================
  # 1. Register the backend keys in your system sops vault tracking array
  # ======================================================================
  sops.secrets = {
    "panix-smtp-password" = {};
    "restic-vault-password" = {};
  };

  # ======================================================================
  # 2. LOCAL BTRFS AUTOMATED SNAPSHOT MATRIX (BTRBK)
  # ======================================================================
  services.btrbk = {
    instances.local = {
      onCalendar = "hourly";
      settings = {
        snapshot_preserve_min = "2d";
        snapshot_preserve = "24h 7d 4w";
        volume."/mnt/btrfs-root" = {
          subvolume = "@home";
          snapshot_dir = ".snapshots/home";
        };
      };
    };
  };

  # =========================================================================
  # 3. DECLARATIVE ATOMIC BACKUPS (NATIVE SYSTEMD RUSTIC CALL ENGINE)
  # Fully custom script pipeline to guarantee atomicity and avoid module blocks.
  # =========================================================================
  systemd.services.rustic-atomic-backup = {
    description = "Atomic Daily Rustic Backup via Btrbk Snapshots";
    
    # ------------------------------------------------------------------------
    # Scheduled to run automatically on system boot or triggered by timers
    # ------------------------------------------------------------------------
    wantedBy = [ "multi-user.target" ];
    
    # ------------------------------------------------------------------------
    # Securely mounts the required runtime tools
    # ------------------------------------------------------------------------
    path = with pkgs; [ coreutils util-linux rustic gnutar gzip ];

    serviceConfig = {
      Type = "oneshot";
      User = "root";
      
      # ------------------------------------------------------------------------
      # ENVIRONMENT INJECTION: Maps repository variables directly into the process layout
      # ------------------------------------------------------------------------
      Environment = [
        "RUSTIC_REPOSITORY=/mnt/5CDbackup/restic-repo"
        "RUSTIC_NON_INTERACTIVE=true"
      ];

      # ------------------------------------------------------------------------
      # EXECUTION PIPELINE RUNNER:
      # Automatically captures your latest hourly btrbk file tree snapshot, mounts it,
      # pushes the encrypted streams over rustic using --as-path, and unmounts cleanly.
      # ------------------------------------------------------------------------
      ExecStart = pkgs.writeShellScript "rustic-atomic-runner" ''
        set -euo pipefail

        # 1. Discover the most recent timestamped subvolume folder generated by btrbk
        LATEST_SNAP=$(ls -td /mnt/btrfs-root/.snapshots/home/@home.* | head -n 1)
        
        if [ -z "$LATEST_SNAP" ]; then
          echo "Error: No btrbk snapshots discovered in pool. Aborting atomic pass."
          exit 1
        fi

        echo "Atomic lock achieved. Binding rustic to static snapshot: $LATEST_SNAP"
        mkdir -p /run/restic-atomic-home
        mount --bind "$LATEST_SNAP" /run/restic-atomic-home

        # 2. Fetch your secure sops vault repository password token key
        export RUSTIC_PASSWORD=$(cat ${config.sops.secrets."restic-vault-password".path})

        # 3. Inspects if the physical config file exists inside the target directory path.
        # If missing, it triggers rustic init safely without breaking the set -e barrier.
        if [ ! -f "/mnt/5CDbackup/restic-repo/config" ]; then
          echo "No active config asset found at target path. Initializing fresh repository pool..."
          rustic init
        fi

        # 4. Execute the modern Rust backup compression sequence
        echo "Initiating rustic data synchronization..."
        rustic backup \
          --as-path=/home/rik \
          --glob="!/run/restic-atomic-home/Downloads" \
          --glob="!/run/restic-atomic-home/.cache" \
          --glob="!/run/restic-atomic-home/Dropbox" \
          /run/restic-atomic-home

        echo "Backup stream transmission completed successfully."
      '';

      # ------------------------------------------------------------------------
      # POST-EXECUTION HOOK: Guarantees that the temporary folder unmounts even if rustic fails
      # ------------------------------------------------------------------------
      ExecStopPost = pkgs.writeShellScript "rustic-atomic-cleanup" ''
        echo "Tearing down atomic runtime namespaces..."
        umount /run/restic-atomic-home || true
        rmdir /run/restic-atomic-home || true
      '';
    };
  };

  # =========================================================================
  # 4. AUTOMATED SYSTEMD BACKUP SCHEDULER TIMER
  # =========================================================================
  # Triggers the custom atomic rustic task automatically once every single day.
  systemd.timers.rustic-atomic-backup = {
    description = "Timer for Atomic Daily Rustic Backups";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true; # Fires missed backup intervals instantly if laptop was closed
    };
  };

  # ======================================================================
  # 4. PANIX OUTBOUND EMAIL TRANSIT PIPELINE (MSMTP)
  # ======================================================================
  programs.msmtp = {
    enable = true;
    accounts = {
      default = {
        host = "mail.panix.com";
        port = 587; # Standard secure submission port
        tls = true;
        tls_starttls = true;
        auth = true;
        user = "rik"; # Your actual panix system username string
        passwordeval = "cat ${config.sops.secrets."panix-smtp-password".path}";
      };
    };
  };
}
