# home/modules/desktop-integration/cosmic-snapshot.nix
#
# COSMIC settings as a committed snapshot, the same workflow as Noctalia's
# exported noctalia.toml: change things in COSMIC Settings, run
# `cosmic-export`, commit the asset, and the next build carries it forward.
# Per-user by construction: the snapshot is assets/<username>/cosmic.toml,
# and `cosmic-export` writes back to that same file in the user's checkout
# of this repo, so enabling it is all a user's home-*.nix needs to do.
#
# COSMIC has no single config file -- every setting is its own RON file
# under ~/.config/cosmic/<component>/v<N>/<entry>. cosmic-ctl
# (nixpkgs#cosmic-ext-ctl, also the engine behind cosmic-manager) can dump
# them all with `backup` and write them back with `apply`. It writes plain
# files, not Home Manager's read-only store symlinks, so COSMIC Settings
# keeps working; and `apply` only touches entries present in the snapshot.
#
# Applied only when the snapshot *changes*, not on every switch: the
# nightly upgrade stages a generation that activates at the next boot, and
# re-applying unconditionally there would silently revert any Settings
# tweak made since the last export. Instead the store path of the applied
# snapshot is stamped under $XDG_STATE_HOME, and apply runs only when it
# differs -- i.e. when the asset itself was edited or re-exported. Exporting
# and then tweaking further before the next build *will* revert those later
# tweaks, since the exported file is newer than what was applied.
#
# `cosmic-export` normalises cosmic-ctl's output before writing it: raw
# backups come out in a different component order on every run (and some
# components carry both a v1 and a v2), which would make every export look
# like a full rewrite in git. Sorting by (dir, component, version) and by
# entry name makes repeated exports byte-identical, and multi-line strings
# keep the RON values readable in diffs.
#
# Only $XDG_CONFIG_HOME is captured. $XDG_STATE_HOME holds window sizes,
# recent files and similar churn -- but also the chosen wallpaper
# (com.system76.CosmicBackground), which is therefore not carried.
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.desktop.cosmicSnapshot;
  assetRel = "assets/${config.home.username}/cosmic.toml";
  cosmic-ctl = lib.getExe' pkgs.cosmic-ext-ctl "cosmic-ctl";
  snapshot = "${cfg.file}";
  stamp = "${config.xdg.stateHome}/cosmic-snapshot/applied";

  cosmic-export =
    pkgs.writers.writePython3Bin "cosmic-export" {
      libraries = [pkgs.python3Packages.tomli-w];
      # The interpolated store paths below can't be wrapped to 79 columns.
      flakeIgnore = ["E501"];
    } ''
      import json
      import os
      import subprocess
      import sys
      import tempfile

      import tomli_w

      HEADER = (
          "# Generated by cosmic-export -- see home/modules/"
          "desktop-integration/cosmic-snapshot.nix.\n"
          "# Re-export rather than hand-editing where possible.\n\n"
      )

      dest = sys.argv[1] if len(sys.argv) > 1 else ${builtins.toJSON cfg.exportPath}
      if not dest:
          sys.exit("usage: cosmic-export <file.toml>")

      with tempfile.TemporaryDirectory() as tmp:
          raw = os.path.join(tmp, "backup.json")
          subprocess.run(
              ["${cosmic-ctl}", "backup", "--xdg-dirs", "config", raw],
              check=True,
              stdout=subprocess.DEVNULL,
          )
          with open(raw) as f:
              data = json.load(f)

      data["operations"].sort(
          key=lambda o: (o["xdg_directory"], o["component"], o["version"])
      )
      for op in data["operations"]:
          op["entries"] = dict(sorted(op["entries"].items()))

      tmp_dest = dest + ".tmp"
      with open(tmp_dest, "w") as f:
          f.write(HEADER + tomli_w.dumps(data, multiline_strings=True))
      os.replace(tmp_dest, dest)
      print(f"cosmic-export: {len(data['operations'])} components -> {dest}")
    '';
in {
  options.desktop.cosmicSnapshot = {
    enable = lib.mkEnableOption "applying a committed COSMIC settings snapshot";

    file = lib.mkOption {
      type = lib.types.path;
      default = ../../.. + "/${assetRel}";
      defaultText = lib.literalExpression ''../../.. + "/assets/''${config.home.username}/cosmic.toml"'';
      description = "cosmic-ctl snapshot (TOML) to apply when it changes.";
    };

    repoDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/Projects/datum/datum-config";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/Projects/datum/datum-config"'';
      description = "This user's working copy of the config repo.";
    };

    exportPath = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.repoDir}/${assetRel}";
      defaultText = lib.literalExpression ''"''${repoDir}/assets/''${config.home.username}/cosmic.toml"'';
      description = ''
        Where `cosmic-export` writes when called without an argument --
        the working-copy path of `file`, so a fresh export lands in the
        repo ready to commit.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [pkgs.cosmic-ext-ctl cosmic-export];

    # After linkGeneration so Home Manager has already removed any old
    # symlinks into ~/.config/cosmic before cosmic-ctl writes there. A
    # failed apply warns instead of aborting the activation (which may be
    # running unattended at boot), and leaves the stamp alone so the next
    # activation retries.
    home.activation.applyCosmicSnapshot = lib.hm.dag.entryAfter ["linkGeneration"] ''
      stamp=${lib.escapeShellArg stamp}
      if [[ "$(cat "$stamp" 2>/dev/null || true)" != ${snapshot} ]]; then
        if run ${cosmic-ctl} apply ${snapshot}; then
          run mkdir -p "$(dirname "$stamp")"
          if [[ ! -v DRY_RUN ]]; then
            printf '%s\n' ${snapshot} > "$stamp"
          fi
        else
          warnEcho "cosmic-ctl apply failed; COSMIC snapshot not applied"
        fi
      else
        verboseEcho "COSMIC snapshot unchanged since last apply; leaving live settings alone"
      fi
    '';
  };
}
