# home/modules/desktop-integration/noctalia.nix
#
# Noctalia (github:noctalia-dev/noctalia): the desktop shell (bar, launcher,
# control center, notifications, lock screen, wallpaper) that pairs with the
# Umbriel compositor enabled in modules/nixos/desktop/umbriel.nix. This is
# per-user rather than system-wide, matching this repo's split between
# system privileges and Home Manager config -- pick the "Umbriel" session at
# cosmic-greeter and Noctalia starts inside it via this systemd user
# service; other sessions (COSMIC) are unaffected.
_: {
  programs.noctalia = {
    enable = true;
    systemd.enable = true;

    # Baseline config carried over from an earlier hand-tuned experiment,
    # not generated by this module. Noctalia's own settings UI is still the
    # right place for further tweaks; re-export from there and drop the
    # result back into assets/noctalia.toml to update this baseline.
    settings = ../../../assets/noctalia.toml;
  };
}
