# ~/Projects/datum-config/backups.nix
{
  config,
  pkgs,
  ...
}: {
  # ======================================================================
  # 1. LOCAL BTRFS AUTOMATED SNAPSHOT MATRIX (BTRBK)
  # ======================================================================
  services.btrbk = {
    instances.local = {
      onCalendar = "hourly";
      settings = {
        # Active retention logic boundaries
        snapshot_preserve_min = "2d";
        snapshot_preserve = "24h 7d 4w";

        # --- INFRASTRUCTURE AUTOMATION CONTROLS ---
        # Forces btrbk to actively scan and adopt/prune unmanaged files in the directory
        snapshot_create = "ondemand";
        archive_preserve_min = "latest";
        archive_preserve = "7d 4w";
        lockfile = "/run/btrbk.lock";

        volume."/mnt/btrfs-root" = {
          subvolume = "@home";
          snapshot_dir = ".snapshots/home";
        };
      };
    };
  };

  # =========================================================================
  # 2. DECLARATIVE ATOMIC BACKUPS (NATIVE SYSTEMD RUSTIC CALL ENGINE)
  # =========================================================================
  systemd.services.rustic-atomic-backup = {
    description = "Atomic Daily Rustic Backup via Btrbk Snapshots";

    # Ensures the backup service won't execute if the physical backup mount goes offline
    requires = ["mnt-5CDbackup.mount"];
    after = ["multi-user.target" "mnt-5CDbackup.mount"];
    onFailure = ["status-email-alert@%n.service"];

    path = with pkgs; [coreutils util-linux rustic gnutar gzip];

    serviceConfig = {
      Type = "oneshot";
      User = "root";

      # ENVIRONMENT INJECTION: Maps repository variables directly into the process layout
      Environment = [
        "RUSTIC_REPOSITORY=/mnt/5CDbackup/restic-repo"
        "RUSTIC_NON_INTERACTIVE=true"
      ];

      # SECURE ROADMAP: Feeds rustic your secret file path strictly at runtime execution,
      # keeping the plain string out of the world-readable /nix/store directory.
      EnvironmentFile = config.sops.secrets."restic-vault-password".path;

      ExecStart = pkgs.writeShellScript "rustic-atomic-runner" ''
        set -euo pipefail

        # 1. Discover the most recent timestamped subvolume folder generated by btrbk
        # Use find + sort to handle unexpected blank states or space chars robustly
        LATEST_SNAP=$(find /mnt/btrfs-root/.snapshots/home/ -maxdepth 1 -type d -name "@home.*" | sort -r | head -n 1)

        if [ -z "$LATEST_SNAP" ]; then
          echo "Error: No btrbk snapshots discovered in pool. Aborting atomic pass."
          exit 1
        fi

        echo "Atomic lock achieved. Binding rustic to static snapshot: $LATEST_SNAP"
        mkdir -p /run/restic-atomic-home
        mount --bind "$LATEST_SNAP" /run/restic-atomic-home

        # 2. Inspects if the physical config file exists inside the target directory path.
        if [ ! -f "/mnt/5CDbackup/restic-repo/config" ]; then
          echo "No active config asset found at target path. Initializing fresh repository pool..."
          rustic init
        fi

        # Administrator profile backup pipeline (rik)
        if [ -d "/run/restic-atomic-home/rik" ]; then
          echo "Syncing profile dataset: rik..."
          rustic backup \
            --as-path=/home/rik \
            --tag="user:rik" \
            --glob="!/run/restic-atomic-home/rik/Downloads" \
            --glob="!/run/restic-atomic-home/rik/.cache" \
            --glob="!/run/restic-atomic-home/rik/Dropbox" \
            /run/restic-atomic-home/rik
        fi

        # Guest profile backup pipeline (guest)
        if [ -d "/run/restic-atomic-home/guest" ]; then
          echo "Syncing profile dataset: guest..."
          rustic backup \
            --as-path=/home/guest \
            --tag="user:guest" \
            --glob="!/run/restic-atomic-home/guest/.cache" \
            /run/restic-atomic-home/guest
        fi

        echo "Backup stream transmission completed successfully."
      '';

      # Post-execution hook, in case rustic fails
      ExecStopPost = pkgs.writeShellScript "rustic-atomic-cleanup" ''
        echo "Tearing down atomic runtime namespaces..."
        if mountpoint -q /run/restic-atomic-home; then
          umount /run/restic-atomic-home
        fi
        rmdir /run/restic-atomic-home || true
      '';
    };
  };

  # =========================================================================
  # 3. AUTOMATED SYSTEMD BACKUP SCHEDULER TIMER
  # =========================================================================
  systemd.timers.rustic-atomic-backup = {
    description = "Timer for Atomic Daily Rustic Backups";
    wantedBy = ["timers.target"];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };

  # ======================================================================
  # 4. PANIX OUTBOUND EMAIL TRANSIT PIPELINE (MSMTP)
  # ======================================================================
  programs.msmtp = {
    enable = true;
    accounts = {
      default = {
        host = "mail.panix.com";
        port = 587;
        tls = true;
        tls_starttls = true;
        auth = true;
        user = "rik";
        passwordeval = "cat ${config.sops.secrets."panix-smtp-password".path}";
      };
    };
  };
  # =========================================================================
  # 5. GLOBAL SYSTEMD FAILURE EMAIL NOTIFIER
  # Automatically triggers on service drops and dispatches status via msmtp
  # =========================================================================
  systemd.services."status-email-alert@" = {
    description = "Status Email Alert Handler for %i";
    path = with pkgs; [coreutils systemd msmtp];
    serviceConfig = {
      Type = "oneshot";
      User = "root"; # Runs as root to read systemd logs securely
      ExecStart = pkgs.writeShellScript "systemd-email-alert" ''
                set -euo pipefail

                # Get the logs for the service that failed
                SERVICE_LOGS=$(journalctl -u "%i" -n 50 --no-pager)

                # Construct a clean email payload
                # Note: msmtp looks for a blank line after headers to identify the message body
                cat <<EOF | msmtp --account=default rik@panix.com
        From: status-alert@datum-laptop.local
        To: rik@panix.com
        Subject: [SYSTEMD ALERT] %i has FAILED on datum-laptop

        The systemd service unit "%i" has entered a failed state.

        -----------------------------------------------------------------
        LAST 50 LOG ENTRIES FROM JOURNAL:
        -----------------------------------------------------------------
        $SERVICE_LOGS
        EOF
                echo "Alert dispatch completed for failure event instance: %i"
      '';
    };
  };
}
